### ISSUE TITLE
"Notifications" action doesn't refresh

### ISSUE THREAD

**Issue by benjymous** [benjymous/MWM-for-Android#31]
If you have the "Recent notifications" action open, then receive a notification, the new one doesn't appear in the list until you close and re-open it.

**Comment by firetech** [comment]
My bad. There is code in place for this, but it broke while I was refactoring and changed from an actionsStack to a containerStack. The check compares the wrong objects now...

**Comment by benjymous** [comment]
Cool.  Please feel free to create issues for any other problems you notice, btw

**Comment by firetech** [comment]
Fixed in Pull Request #32
