### ISSUE TITLE
Widgets from external sources don't refresh properly when on an Idle page > #0

### ISSUE THREAD

**Issue by benjymous** [benjymous/MWM-for-Android#33]
Reproduction steps:
- Build and install the MWM Api demos project ( https://github.com/benjymous/ApiDemos-MWM )
- Add an instance of the Api Demos widget to the initial idle screen
- Add an instance of the widget to a secondary (clockless) idle screen
- Click the "Update Widget" button in the Api demos app - note that the widget on the initial idle screen will refresh, but ones on secondary (clockless) screens don't update unless you switch away from the page the go back.

**Comment by benjymous** [comment]
It seems to work fine when the "clock on all idle pages" option is checked - so might be related to using app mode for clockless pages

**Comment by firetech** [comment]
There is a setting for that as well, did you try changing it?

**Comment by benjymous** [comment]
If the "always show clock" option is ticked, the external widgets refresh as expected, with it off, no matter how the "app buffer" option is set, they don't refresh properly.

**Comment by firetech** [comment]
Ok. That is seriously messed up. I read through relevant parts of the
code and found nothing enlightening... :S

On 3 June 2012 21:12, benjymous
reply@reply.github.com
wrote:

> If the "always show clock" option is ticked, the external widgets refresh as expected, with it off, no matter how the "app buffer" option is set, they don't refresh properly.
>

**Comment by firetech** [comment]
I'm closing in on the bug. There are two reasons that make this happen:
1. Widgets are only updated when the used buffer is set to the IDLE buffer.
2. The "Use App Buffer" setting doesn't work (it's always true).

**Comment by firetech** [comment]
Fixed with commits 9184901 and 11e533a, respectively.
