### ISSUE TITLE
SharedPreferences.Editor.apply() doesn't exist in 2.2 and earlier

### ISSUE THREAD

**Issue by benjymous** [benjymous/MWM-for-Android#38]
We're using Editor.apply in InternalApp.setPageSetting(InternalApp.java:62) - this causes the app to crash on 2.2 or earlier, as that function doesn't exist.

java.lang.NoSuchMethodError: android.content.SharedPreferences$Editor.apply

Suggest either catching and doing a commit() instead, or just doing commit() on its own

**Comment by firetech** [comment]
Either way, the method that uses it is mostly just a temporary solution until a better app selection framework is in place ;)

**Comment by firetech** [comment]
But yeah, changing it to a commit() should be fine. I didn't notice the high API level of apply()...

**Comment by benjymous** [comment]
It does look like very few people are using anything below 2.3, thankfully, as that's the first time it's triggered in BugSense, out of 155 downloads of rm15 and rm15a

**Comment by benjymous** [comment]
Fixed in commit 1beb20f792c62b58d80938e588564ef9cde1fd73
