### ISSUE TITLE
Other Apps notifications in Jelly Bean

### ISSUE THREAD

**Issue by firetech** [benjymous/MWM-for-Android#40]
The Accessibility service intents seem to have changed in Jelly Bean.

On my Galaxy Nexus I've gotten up to 10 duplicates of the same notification...

**Comment by benjymous** [comment]
Nasty.  But a simple thing to fix, I guess - just keep a cache of the last notification details for each app, and only display if it's new.

Do we have access to the notification's creation time?

**Comment by firetech** [comment]
On 5 July 2012 17:02, benjymous
reply@reply.github.com
wrote:

> Nasty.  But a simple thing to fix, I guess - just keep a cache of the last notification details for each app, and only display if it's new.
> 
> Do we have access to the notification's creation time?

I don't know. Also, I don't know if the actual notification object is
the same for all the intents. I haven't gotten to debugging it yet. ;)

**Comment by firetech** [comment]
This actually seems to be a bug in Jelly Bean. After reinstalling MWM, the
repetitions are down to one or two. I've also had to disable and reenable
the MetaWatch accessibility service a few times. Might be related. Android
may be running multiple accessibility service instances...

**Comment by firetech** [comment]
Fixed in d1da00b.

In a _highly_ unlikely scenario, two apps can send notifications exactly at the same time and still trigger the bug (by switching the stored values back and forth), but I don't think that will happen more than once in our (watches') lifetime.

I still haven't figured out an exact way to trigger the bug, but some combinations of the following (with some actions repeated) have been somewhat successful:
- Toggling the Accessibility service while MWM is running.
- Exiting MWM and toggling the Accessibility service (while MWM is NOT running).
- Ending the MWM app using a task manager (such as Advanced Task Manager, NOT using "Force stop" from settings).
