### ISSUE TITLE
Geolocation failing

### ISSUE THREAD

**Issue by benjymous** [benjymous/MWM-for-Android#47]
(May be related to #46)

Currently when I have geolocation enabled, it fails to refresh the weather, with the following error in the logcat

Java.io.IOException: Unable to parse response from server

at android.location.Geocoder.getFromLocation(Geocoder.java:136)
at org.metawatch.manager.AbstractWeatherEngine.reverseLookupGeoLocation(AbstractWeatherEngine.java:53)

That seems to suggest that Google's service itself is down - it was working fine all of yesterday!

**Comment by dedee** [comment]
The Google service recognizes sometimes if you use the webservice too often and declines further requests. This is most probably the reason for this. With my changes maybe this is now more obvious. Maybe we could "cache" the location for some time. And we could check if we need to slow down the weather update cycles.

**Comment by benjymous** [comment]
Aha, that would make sense - it has checks that prevents too many requests, but only when they're actually successful.  I've closed MWM on my phone for a while, and see if it works again in a couple of hours.

Is there an option to make it use the Wunderground geolocation again?

**Comment by benjymous** [comment]
I've had a quick flick through the code, and am going to add an option to choose how geolocation works (so change the current off/on checkbox to off/always use google/use provider, so the user can choose to use wunderground's own geolocation if they prefer)

I've also noticed another issue - previously when geolocation was enabled but no location had been received yet, the wundeground code would just abort, as it will get refreshed when a location is received.  Now it falls back to the manually entered location instead (which may be Dallas), which means the user will be stuck with weather from totally the wrong location for ~30 minutes until the next refresh.

I'll fix that too, and comment back how I get on!

**Comment by benjymous** [comment]
Yup, that seems to have fixed it - I'll commit the changes this evening, once I'm happy I haven't broken something else!

**Comment by dedee** [comment]
Thats cool!
