### ISSUE TITLE
Wunderground Weather without geo location

### ISSUE THREAD

**Issue by dedee** [benjymous/MWM-for-Android#51]
In the current implementation comma char is being ignored

By default we use weather location "DALLAS,US"

This location is converted to this URL: http://api.wunderground.com/api/1df3eaacab9abc8a/geolookup/conditions/forecast10day/astronomy/q/DallasUS.json

Wunderground does not return valid data (also when entered in a browser).

When I am using the location string "DALLAS TX" it is working properly.
http://api.wunderground.com/api/1df3eaacab9abc8a/geolookup/conditions/forecast10day/astronomy/q/Dallas%20TX.json

**Comment by benjymous** [comment]
Have changed it to replace commas with spaces, and changed the default location to "DALLAS TX" instead of "DALLAS,US"

**Comment by benjymous** [comment]
Fixed with above commit and 12bb389ae422aab1797cfd944d9b586367d611a2
