### ISSUE TITLE
Blutooth dropout

### ISSUE THREAD

**Issue by sdemills** [benjymous/MWM-for-Android#76]
Since the Community update on Google Play this week, the BT connection with the watch keeps dropping out. Sometimes after only 10 minutes, sometimes nearer an hour. MW freshly charged. Phone (Samsung GS2) freshly charged too.

**Comment by sdemills** [comment]
Update: I normally use Juice Defender Ultimate and it was running at the time. I do not normally experience any clashes between JD and MWM. Anyway, today I'm trying it with JD deactivated and will update later as to whether it still keeps dropping out.

**Comment by benjymous** [comment]
Thanks. 

If possible, could you compare against the previous versions, to see if you can spot exactly when it started misbehaving?

**Comment by sdemills** [comment]
Maybe you might be able to advise? If I pull a version from GitHub and
build it (my dev environment is geared up for that - so no issue there)
then presumably I need to uninstall the one from Google Play, install and
test my built one, then uninstall that and re-install the Google Play
version? In the process, will I lose all my settings? I ask the last
question because in the past I've saved the settings but newer versions
have sometimes been unable to load them - understandably of course when
things change significantly :)

**Comment by benjymous** [comment]
You don't need to rebuild it yourself - all the previous versions are archived on the downloads page here on github

If you're building it yourself, use the backup settings option, then copy the data/org.metawatch.communityedition dir on your sd card (as it'll get nuked when you uninstall the Play version) then you can uninstall, build your own version, copy that folder back, then run the restore option.

**Comment by sdemills** [comment]
Thanks for the advice. Presumably ASTRO App Backup facility would also
work? Then restore afterwards?

**Comment by benjymous** [comment]
Yeah, any root backup type app should work - I use Titanium Backup if I need to switch from a debug built version to the store released one

**Comment by sdemills** [comment]
This is no longer happening after the recent updates so I reckon we should close this.
