### ISSUE TITLE
MWM watch app framework

### ISSUE THREAD

**Issue by sdemills** [benjymous/MWM-for-Android#78]
Is there any plan to have a framework for pluggable watch apps?

It would be good to be able to install an app that could register with MWM so that it would appear in the list of apps so that it could be selected in MWM and used just like the others in the MWM? I was originally going to add some apps into MWM but it looks like things are heading towards a framework and/or SDK. If that's the case then I should wait.

**Comment by benjymous** [comment]
There already is one - check out the ApiDemos and MetaNeko projects in my github for examples.

**Comment by sdemills** [comment]
Thanks Richard. That was exactly what I was looking for. I'll knock up a
couple of test apps to prove that I've figured it properly, and then start
on some proper designs. When I'm done I shall make them freely available
for anyone that wants them.

**Comment by sdemills** [comment]
Just thought I'd close this one off: I followed your examples for Watch App and Widget and both worked fine. So I'm going to see what I can build now :) Thanks for your help.
